# coding: utf-8

"""
    K-mer Search API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kmersearch-api-client
from kmersearch-api-client.models.sample import Sample  # noqa: E501
from kmersearch-api-client.rest import ApiException


class TestSample(unittest.TestCase):
    """Sample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSample(self):
        """Test Sample"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kmersearch-api-client.models.sample.Sample()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
