# coding: utf-8

"""
    K-mer Search API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kmersearch_api_client
from kmersearch_api_client.models.samples import Samples  # noqa: E501
from kmersearch_api_client.rest import ApiException


class TestSamples(unittest.TestCase):
    """Samples unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSamples(self):
        """Test Samples"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kmersearch_api_client.models.samples.Samples()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
